### ISSUE TITLE
Add mailgun support to the hall monitor

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/ALActions#14]
MLH has a general mailgun account instead of sendgrid. The request seems just as simple; there isn't a python library, but it looks like it should work through [`requests` and JSON](https://documentation.mailgun.com/en/latest/api-sending.html#sending). We should be able to have two different actions steps, depending on if people set up a SENDGRID or MAILGUN API key, and do the appropriate JSON then. It'd be nice if they could share code, maybe I start calling into a separate python file, which would be cleaner to read anyway.

**Comment by nonprofittechy** [comment]
Just a thought for future enhancements: the API is definitely better/faster/cleaner, but before supporting another tool I'd just support plain old SMTP, which both Mailgun and Sendgrid also support.
