### ISSUE TITLE
Black formatting is failing

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/ALActions#19]
https://github.com/SuffolkLITLab/docassemble-AssemblyLine/actions/runs/7182833153/job/19560413472

The issue is upstream, and looks like it needs to be fixed in that repo. Our options are:

* fix upstream, wait for it to be merged
* fix upstream, fork and run our own
* switch to the [`psf/black` action](https://black.readthedocs.io/en/stable/integrations/github_actions.html), as actually recommend in the [README of our current action](https://github.com/rickstaa/action-black#action-black-github-action). I have a quick fix in https://github.com/SuffolkLITLab/ALActions/tree/new_black, but I'm not sure how to get the pull request part working again; getting whether it's a feature the official action doesn't have. I can try to keep going on this one, as I think the upstream support will be stronger for the official action

I'll keep going on 3, unless there's any objections or other suggestions. @nonprofittechy

**Comment by nonprofittechy** [comment]
3 sounds good to me!
