### ISSUE TITLE
Add a script to initialize an empty Docassemble repo?

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/ALActions#3]
This feels like it might be the right place to put a script that initializes an empty Github repo with the boilerplate stuff for a Docassemble repo, so that you don't need to start in the DA playground. Personally I'd find that pretty useful. An alternative would be on the docassemblecli repo itself

**Comment by BryceStevenWilley** [comment]
I think the question for if that belongs here is "how does it run?"  This repo is mostly for github actions and things that need to run org-wide routinely.  I think that it going in docassemblecli would be better.
